run:
	python manage.py runserver


make_migrations:
	python manage.py makemigrations


migrate:
	python manage.py migrate

shell_plus:
	python manage.py shell_plus --print-sql

celery:
	celery -A blog worker -l info