# Generated by Django 3.1.7 on 2021-03-28 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50, verbose_name='The title of your masterpiece')),
                ('description', models.CharField(max_length=90, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Paste ors Write it here :) ')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='first name')),
                ('email', models.CharField(max_length=20, verbose_name='email')),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
