# Generated by Django 3.0.3 on 2021-04-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210414_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('time_execution', models.DateTimeField()),
                ('path', models.TextField(verbose_name='path')),
                ('utm', models.CharField(max_length=20, verbose_name='utm')),
                ('i_p', models.GenericIPAddressField()),
            ],
        ),
    ]
