# Generated by Django 3.0.3 on 2021-04-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='created',
            field=models.CharField(max_length=20, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='i_p',
            field=models.CharField(max_length=20, verbose_name='utm'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='time_execution',
            field=models.CharField(max_length=20, verbose_name='created time'),
        ),
    ]
