# Generated by Django 3.0.3 on 2021-04-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
